backend:
  name: git-gateway
media_folder: images
public_folder: images
collections:
  - name: "sections"
    label: "Sections"
    extension: "json"
    format: "json"
    files:
      - file: "data/performances.json"
        name: "performances"
        label: "Performances"
        widget: "list"
        fields:
          - { label: "Time", name: "time" }
          - { label: "Genre", name: "genre" }
          - { label: "Group Name", name: "group" }
          - { label: "Performance Name", name: "name" }
