backend:
  name: git-gateway
media_folder: images
public_folder: images
collections:
  - name: "sections"
    label: "Sections"
    extension: "json"
    format: "json"
    files:
      - file: "data/performances.json"
        name: "performances"
        label: "Performances"
        fields:
          - label: "Performance"
            name: "performance"
            widget: "list"
            fields:
              - { label: "Time", name: "time" }
              - { label: "Genre", name: "genre", required: false }
              - { label: "Group Name", name: "group", required: false }
              - { label: "Performance Name", name: "name", required: false }
